name: CI for TDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # Checks out repository under $GITHUB_WORKSPACE, so the workflow can access it.

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        # Uses the setup-java action to configure the Java environment.
        with:
          java-version: '19'
          distribution: 'temurin'
          # Specifies the Java version and distribution to use.

      - name: Build with Maven
        run: mvn -B clean package -DskipTests -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
        # Executes Maven commands to clean, compile, and package the application, skipping tests.

      - name: Test with Maven
        run: mvn -B test -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
        # Executes Maven to run the project's tests.

      - name: Run PIT Mutation Test
        run: mvn clean test-compile org.pitest:pitest-maven:mutationCoverage
        # Executes PITest to generate mutation coverage reports.